///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppAssets {
  AppAssets._();

  static const String fontsClashDisplayMedium =
      'assets/fonts/ClashDisplay-Medium.ttf';
  static const String fontsSatoshiMedium = 'assets/fonts/Satoshi-Medium.ttf';
  static const String fontsTelmaMedium = 'assets/fonts/Telma-Medium.ttf';
  static const String translationsAr = 'assets/translations/ar.json';
  static const String translationsEn = 'assets/translations/en.json';
}
